id = "test"
name = "Test Driver"
desc = "use test driver read all png"
icon = "test.png"
author = ["author1(author1@email.com)", "author2(author2@email.com)"]
version = "v1.2.3"
released_time = "2024.10.12"
changelog = ["1.优化testdriver 链接", "2.修改bug"]
